sudo: false
language: node_js
node_js:
  - '11'
  - '10'
  - '8'
  - '6'
  - '4'
script:
  - "npm run test-travis"
after_script:
  - "npm install coveralls@3 && cat coverage/lcov.info | coveralls"
notifications:
  email: a@alexandresaiz.com
